# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CommTypes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CommTypes.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x43ommTypes.proto\"\x9b\x01\n\rprotoSpeedSSL\x12\n\n\x02vx\x18\x01 \x01(\x01\x12\n\n\x02vy\x18\x02 \x01(\x01\x12\n\n\x02vw\x18\x03 \x01(\x01\x12\r\n\x05\x66ront\x18\x04 \x01(\x08\x12\x0c\n\x04\x63hip\x18\x05 \x01(\x08\x12\x0e\n\x06\x63harge\x18\x06 \x01(\x08\x12\x14\n\x0ckickStrength\x18\x07 \x01(\x01\x12\x10\n\x08\x64ribbler\x18\x08 \x01(\x08\x12\x11\n\tdribSpeed\x18\t \x01(\x01\"3\n\x10protoPositionSSL\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01w\x18\x03 \x01(\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PROTOSPEEDSSL = _descriptor.Descriptor(
  name='protoSpeedSSL',
  full_name='protoSpeedSSL',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vx', full_name='protoSpeedSSL.vx', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vy', full_name='protoSpeedSSL.vy', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vw', full_name='protoSpeedSSL.vw', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='front', full_name='protoSpeedSSL.front', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chip', full_name='protoSpeedSSL.chip', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='charge', full_name='protoSpeedSSL.charge', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kickStrength', full_name='protoSpeedSSL.kickStrength', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dribbler', full_name='protoSpeedSSL.dribbler', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dribSpeed', full_name='protoSpeedSSL.dribSpeed', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=175,
)


_PROTOPOSITIONSSL = _descriptor.Descriptor(
  name='protoPositionSSL',
  full_name='protoPositionSSL',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='protoPositionSSL.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='protoPositionSSL.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w', full_name='protoPositionSSL.w', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=228,
)

DESCRIPTOR.message_types_by_name['protoSpeedSSL'] = _PROTOSPEEDSSL
DESCRIPTOR.message_types_by_name['protoPositionSSL'] = _PROTOPOSITIONSSL

protoSpeedSSL = _reflection.GeneratedProtocolMessageType('protoSpeedSSL', (_message.Message,), dict(
  DESCRIPTOR = _PROTOSPEEDSSL,
  __module__ = 'CommTypes_pb2'
  # @@protoc_insertion_point(class_scope:protoSpeedSSL)
  ))
_sym_db.RegisterMessage(protoSpeedSSL)

protoPositionSSL = _reflection.GeneratedProtocolMessageType('protoPositionSSL', (_message.Message,), dict(
  DESCRIPTOR = _PROTOPOSITIONSSL,
  __module__ = 'CommTypes_pb2'
  # @@protoc_insertion_point(class_scope:protoPositionSSL)
  ))
_sym_db.RegisterMessage(protoPositionSSL)


# @@protoc_insertion_point(module_scope)
